### ISSUE TITLE
Build with session cookie and crumb

### ISSUE THREAD

**Issue by gitqlt** [nottsgeek/jenkins_job#1]
# With Jenkins 2.263.1 (docker image)
# (See: https://support.cloudbees.com/hc/en-us/articles/219257077-CSRF-Protection-Explained)
```
  - name: Get crumb and session cookie
    uri:
      url: "http://<<yourip:port>>/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,%22:%22,//crumb)"
      method: GET
      user: "{{ Uname }}"
      password: "{{ Pass }}"
      force_basic_auth: yes
      status_code: 200
      return_content: yes
    register: cookiecrumb

  - name: Queue build
    uri:
      url: http://<<yourip:port>>/job/<<FolderName>>/job/<<JobName>>/build
      method: POST
      user: "{{ Uname }}"
      password: "{{ Pass }}"
      force_basic_auth: yes
      status_code: 201
      headers:
        Cookie: "{{ cookiecrumb.cookies_string }}"
        Jenkins-Crumb: "{{ cookiecrumb.content[14:] }}"
```
